import { exercises as seedExercises } from '../data/exercises.js';
import { templates as seedTemplates } from '../data/templates.js';
import { get, getAll, put, putMany, byIndex } from './db.js';
import { TimestampTimer, formatDuration, now } from './timers.js';
import { makeBackup, restoreBackup, makeSetCsv, download } from './backup.js';

const $ = selector => document.querySelector(selector); const view=$('#view'); const status=$('#status');
const key='hwt-active-v1'; let active=JSON.parse(localStorage.getItem(key)||'null'); let restTimer=new TimestampTimer(active?.restTimer); let tick;
const uid=()=>crypto.randomUUID?.() || `${Date.now()}-${Math.random().toString(16).slice(2)}`;
const dateFor = timestamp => new Date(timestamp).toLocaleDateString('en-CA');
const saveActive=()=>{ if(active){active.restTimer=restTimer.snapshot;localStorage.setItem(key,JSON.stringify(active));} else localStorage.removeItem(key); };
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function seed(){ if(!(await getAll('exercises')).length) await putMany('exercises',seedExercises); if(!(await getAll('templates')).length) await putMany('templates',seedTemplates); }
function setStatus(message){status.textContent=message;}
function interval(){clearInterval(tick);tick=setInterval(async()=>{if(!active)return;const session=await get('workoutSessions',active.sessionId);const workoutClock=$('.workout-elapsed');if(session&&workoutClock)workoutClock.textContent=formatDuration(now()-session.startTimestamp);const restClock=$('.rest-countdown');if(restClock){const remaining=restTimer.remaining();if(!remaining)renderWorkout();else restClock.textContent=formatDuration(remaining);}},1000);}
function restBlock(){ if(!restTimer.snapshot) return ''; const remaining=restTimer.remaining(); if(!remaining){ if(active.restTimer?.notified!==true){ active.restTimer.notified=true; saveActive(); navigator.vibrate?.([120,70,120]); } return `<div class="card"><h3 class="complete">Rest complete</h3><div class="timer">00:00</div><button data-action="clear-rest">Continue</button></div>`; } return `<div class="card"><span class="pill">REST</span><div class="timer rest-countdown">${formatDuration(remaining)}</div><div class="presets"><button data-action="rest-toggle">${restTimer.snapshot.status==='paused'?'Resume':'Pause'}</button><button data-action="rest-add">+30s</button><button data-action="clear-rest">Skip</button><button data-action="rest-120">120s</button></div></div>`; }
async function renderWorkout(){
  if(!active){ const templates=await getAll('templates'); view.innerHTML=`<div class="card"><h2>Ready to train?</h2><p>Sessions, sets, timers, and history are stored on this device.</p><div class="list">${templates.map(t=>`<div class="row"><div><h3>${esc(t.name)}</h3><p>${esc(t.description)}</p></div><button class="primary" data-template="${t.id}">Start</button></div>`).join('')}</div></div>`; return; }
  const session=await get('workoutSessions',active.sessionId); if(!session){active=null;saveActive();return renderWorkout();}
  const template=await get('templates',session.templateId); const allExercises=Object.fromEntries((await getAll('exercises')).map(x=>[x.id,x])); const warmup=template.warmup||[]; const plans=[...warmup.map(id=>({exerciseId:id,warmup:true})),...template.exercises]; const item=plans[active.index];
  if(!item) return renderFinish(session);
  const exercise=allExercises[item.exerciseId]; const prior=await byIndex('exerciseSets','byExercise',exercise.id); const priorText=prior.sort((a,b)=>b.exerciseFinished-a.exerciseFinished)[0]; const setNo=active.setNumber || 1;
  view.innerHTML=`<div class="card"><div class="exercise-count">${active.index+1} / ${plans.length}${item.warmup?' · WARM-UP':''}</div><h2>${esc(exercise.name)}</h2><p>${esc(exercise.defaultRepTarget)} · ${esc(exercise.equipment)}</p><div class="timer workout-elapsed">${formatDuration(now()-session.startTimestamp)}</div><p class="muted">Workout elapsed</p></div>${restBlock()}<div class="card">${item.warmup?`<p>Keep this easy. Record it as completed when ready.</p><div class="actions"><button class="primary" data-action="complete-warmup">Complete warm-up item</button><button class="secondary" data-action="skip-item">Skip</button></div>`:`<div class="exercise-count">SET ${setNo} OF ${item.setTarget}</div><p>${priorText?`Most recent: ${priorText.reps||'—'} reps${priorText.weight?` · ${priorText.weight}${priorText.weightUnit}`:''}`:'No previous set recorded.'}</p>${active.setStartedAt?`<p class="complete">Set in progress · ${formatDuration(now()-active.setStartedAt)}</p>`:''}<div class="fields"><label>Reps<input id="reps" inputmode="decimal" placeholder="${esc(exercise.defaultRepTarget)}"></label><label>Weight<input id="weight" inputmode="decimal" placeholder="0"></label><label>Unit<select id="unit"><option>lb</option><option>kg</option></select></label><label>Assistance<input id="assistance" inputmode="decimal" placeholder="optional"></label></div><label>Set notes<textarea id="set-notes" placeholder="Optional"></textarea></label><div class="actions">${active.setStartedAt?`<button class="primary" data-action="finish-set">Finish set</button>`:`<button class="primary" data-action="start-set">Start set</button>`}<button class="secondary" data-action="skip-item">Skip exercise</button></div>`}</div>`;
}
async function startWorkout(templateId){const template=await get('templates',templateId);const started=now();const session={id:uid(),workoutDate:dateFor(started),startTimestamp:started,endTimestamp:null,templateId,templateName:template.name,totalDuration:null,notes:'',completionStatus:'in-progress',warmupItems:[]};await put('workoutSessions',session);active={sessionId:session.id,index:0,setNumber:1,setStartedAt:null,restTimer:null};saveActive();setStatus('Workout started.');renderWorkout();}
async function advance(){active.index++;active.setNumber=1;active.setStartedAt=null;restTimer=new TimestampTimer();saveActive();renderWorkout();}
async function saveSet(){const reps=$('#reps').value; const finished=now(); const template=await get('templates',(await get('workoutSessions',active.sessionId)).templateId); const plans=[...(template.warmup||[]).map(exerciseId=>({exerciseId,warmup:true})),...template.exercises]; const item=plans[active.index]; if(!reps){setStatus('Enter reps before finishing the set.');return;} const exercise=await get('exercises',item.exerciseId); const duration=finished-active.setStartedAt; const record={id:uid(),workoutSessionId:active.sessionId,exerciseId:exercise.id,setNumber:active.setNumber,startTimestamp:active.setStartedAt,exerciseFinished:finished,setDuration:duration,reps:Number(reps),weight: Number($('#weight').value||0),weightUnit:$('#unit').value,assistanceWeight:Number($('#assistance').value||0),rir:null,notes:$('#set-notes').value,restDuration:exercise.defaultRestDuration};await put('exerciseSets',record);if(active.setNumber>=item.setTarget){active.index++;active.setNumber=1;}else active.setNumber++;active.setStartedAt=null;restTimer.start(exercise.defaultRestDuration*1000);saveActive();renderWorkout();setStatus('Set saved.');}
async function renderFinish(session){view.innerHTML=`<div class="card"><h2>Finish workout</h2><p>End this session and save its final duration.</p><label>Session notes<textarea id="session-notes" placeholder="How did it feel?"></textarea></label><div class="actions two"><button class="primary" data-action="finish-workout">Complete</button><button class="secondary" data-action="end-incomplete">End incomplete</button></div></div>`;}
async function endWorkout(completionStatus){const session=await get('workoutSessions',active.sessionId);session.endTimestamp=now();session.totalDuration=session.endTimestamp-session.startTimestamp;session.completionStatus=completionStatus;session.notes=$('#session-notes')?.value||session.notes;await put('workoutSessions',session);active=null;restTimer=new TimestampTimer();saveActive();setStatus('Workout saved to history.');renderWorkout();}
async function markWarmup(statusValue){const session=await get('workoutSessions',active.sessionId); const template=await get('templates',session.templateId); session.warmupItems.push({exerciseId:template.warmup[active.index],status:statusValue,timestamp:now()});await put('workoutSessions',session);advance();}
async function skip(){const session=await get('workoutSessions',active.sessionId); const template=await get('templates',session.templateId); const plans=[...(template.warmup||[]).map(exerciseId=>({exerciseId,warmup:true})),...template.exercises];session.skippedItems=[...(session.skippedItems||[]),{exerciseId:plans[active.index].exerciseId,timestamp:now()}];await put('workoutSessions',session);advance();}
async function renderHistory(){const [sessions,sets,templates,exercises,cardio]=await Promise.all(['workoutSessions','exerciseSets','templates','exercises','cardioSessions'].map(getAll));const templateById=Object.fromEntries(templates.map(x=>[x.id,x]));const exerciseById=Object.fromEntries(exercises.map(x=>[x.id,x]));const workoutCards=sessions.sort((a,b)=>b.startTimestamp-a.startTimestamp).map(s=>{const own=sets.filter(set=>set.workoutSessionId===s.id);return `<button class="row" data-session="${s.id}"><span><strong>${esc(templateById[s.templateId]?.name||s.templateName)}</strong><br><span class="muted">${esc(s.workoutDate)} · ${formatDuration(s.totalDuration||now()-s.startTimestamp)} · ${own.length} sets</span></span><span>${s.completionStatus==='completed'?'✓':'○'}</span></button>`;}).join('');const cardioCards=cardio.sort((a,b)=>b.timestamp-a.timestamp).map(c=>`<div class="row"><span><strong>${esc(c.type)}</strong><br><span class="muted">${esc(c.date)} · ${c.duration/60} min${c.distance?` · ${c.distance} ${c.distanceUnit}`:''}</span></span><span>Cardio</span></div>`).join('');view.innerHTML=`<h2>History</h2><div class="list">${workoutCards||'<div class="card"><p>No workouts yet.</p></div>'}${cardioCards}</div>`; window.sessionDetail=async id=>{const s=sessions.find(x=>x.id===id);const own=sets.filter(x=>x.workoutSessionId===id);view.innerHTML=`<button data-view="history">← History</button><div class="card"><h2>${esc(templateById[s.templateId]?.name||s.templateName)}</h2><p>${s.workoutDate} · ${formatDuration(s.totalDuration||0)} · ${s.completionStatus}</p>${own.map(x=>`<div class="row"><span><strong>${esc(exerciseById[x.exerciseId]?.name||x.exerciseId)}</strong><br>${x.reps} reps · ${x.weight||'bodyweight'} ${x.weight?x.weightUnit:''}${x.assistanceWeight?` · ${x.assistanceWeight} assist`:''}</span><span>Set ${x.setNumber}</span></div>`).join('')||'<p>No sets recorded.</p>'}</div>`;};}
async function renderCardio(){view.innerHTML=`<div class="card"><h2>Log cardio</h2><div class="fields"><label>Type<select id="cardio-type"><option>walking</option><option>biking</option><option>other</option></select></label><label>Duration (min)<input id="cardio-duration" inputmode="decimal" required></label><label>Distance<input id="cardio-distance" inputmode="decimal"></label><label>Unit<select id="cardio-unit"><option>mi</option><option>km</option></select></label></div><label>Notes<textarea id="cardio-notes"></textarea></label><div class="actions"><button class="primary" data-action="save-cardio">Save cardio</button></div></div>`;}
async function renderData(){view.innerHTML=`<div class="card"><h2>Your data</h2><p>Export a complete backup before changing phones or browsers. Restoring replaces local records only after validation and confirmation.</p><div class="actions"><button class="primary" data-action="backup">Export JSON backup</button><button data-action="csv">Export set CSV</button><label class="row">Restore JSON<input id="restore-file" type="file" accept="application/json" hidden><span class="pill">Choose file</span></label></div></div>`;$('#restore-file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const value=JSON.parse(await file.text());if(!confirm('Replace all local workout data with this validated backup? This cannot be undone.'))return;await restoreBackup(value);active=null;saveActive();setStatus('Backup restored.');renderData();}catch(error){setStatus(error.message);}});}
async function show(name){document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===name));clearInterval(tick);({workout:renderWorkout,history:renderHistory,cardio:renderCardio,data:renderData}[name])();if(name==='workout')interval();}
document.addEventListener('click',async event=>{const button=event.target.closest('button');if(!button)return;if(button.dataset.view)return show(button.dataset.view);if(button.dataset.template)return startWorkout(button.dataset.template);if(button.dataset.session)return window.sessionDetail(button.dataset.session);const action=button.dataset.action;if(!action)return; if(action==='start-set'){active.setStartedAt=now();saveActive();renderWorkout();}if(action==='finish-set')await saveSet();if(action==='complete-warmup')await markWarmup('completed');if(action==='skip-item')await skip();if(action==='finish-workout')await endWorkout('completed');if(action==='end-incomplete')await endWorkout('incomplete');if(action==='rest-toggle'){restTimer.snapshot.status==='running'?restTimer.pause():restTimer.resume();saveActive();renderWorkout();}if(action==='rest-add'){restTimer.add(30000);saveActive();renderWorkout();}if(action==='rest-120'){restTimer.start(120000);saveActive();renderWorkout();}if(action==='clear-rest'){restTimer=new TimestampTimer();saveActive();renderWorkout();}if(action==='save-cardio'){const timestamp=now();await put('cardioSessions',{id:uid(),type:$('#cardio-type').value,duration:Number($('#cardio-duration').value)*60,distance:Number($('#cardio-distance').value||0),distanceUnit:$('#cardio-unit').value,notes:$('#cardio-notes').value,timestamp,date:dateFor(timestamp)});setStatus('Cardio saved.');renderCardio();}if(action==='backup'){download(JSON.stringify(await makeBackup(),null,2),`workout-backup-${dateFor(now())}.json`,'application/json');}if(action==='csv'){download(await makeSetCsv(),`workout-sets-${dateFor(now())}.csv`,'text/csv');}});
await seed(); if('serviceWorker'in navigator) navigator.serviceWorker.register('./service-worker.js'); if(active){const session=await get('workoutSessions',active.sessionId);if(session&&confirm('Resume your in-progress workout? Choose Cancel to end it as incomplete.')){}else if(session){active={sessionId:session.id};await endWorkout('incomplete');}}show('workout');
